<a href="https://colab.research.google.com/github/anshita572/ml_assign/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np;

In [ ]:
#q1
#a
arr=np.array([1,2,3,6,4,5]);
arr=arr[::-1];
arr

array([5, 4, 6, 3, 2, 1])

In [ ]:
#b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]);
array1=array1.flatten();
array1

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [ ]:
#c
arr1 = np.array([[1, 2], [3, 4]]);
arr2 = np.array([[1, 2], [3, 4]]);
np.array_equal(arr1,arr2)

True

In [ ]:
#d
x = np.array([1,2,3,4,5,1,2,1,1,1]);
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]);
maxx=np.bincount(x).argmax();
for i in range(0,x.size):
  if x[i]==maxx:
    print(i," ",maxx);
print("\n");
maxy=np.bincount(y).argmax();
for i in range(0,y.size):
  if y[i]==maxy:
    print(i," ",maxy);

0   1
5   1
7   1
8   1
9   1


0   1
1   1
2   1


In [ ]:
#e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]');
print(np.sum(gfg));
print(np.sum(gfg,axis=1));
print(np.sum(gfg,axis=0));

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
#f
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]);
print(np.trace(n_array));
print(np.linalg.eig(n_array));
print(np.linalg.inv(n_array));
print(np.linalg.det(n_array));

176
(array([98.16835147, 28.097044  , 49.73460452]), array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [ ]:
#g
#(i)
p = [[1, 2], [2, 3]];
q = [[4, 5], [6, 7]];
print(np.matmul(p,q));
print("\n");
print(np.cov(p,q));

[[16 19]
 [26 31]]


[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
#g
#(ii)
p = [[1, 2], [2, 3], [4, 5]];
q = [[4, 5, 1], [6, 7, 2]];
print(np.matmul(p,q));
print("\n");
print(np.cov(p,q));

[[16 19  5]
 [26 31  8]
 [46 55 14]]




ValueError: ignored

In [ ]:
#h
x = np.array([[2, 3, 4], [3, 2, 9]]);
y = np.array([[1, 5, 0], [5, 10, 3]]);
print(np.cross(x,y));
print("\n");
print(np.inner(x,y));
print("\n");
print(np.outer(x,y));

[[-20   4   7]
 [-84  36  20]]


[[17 52]
 [13 62]]


[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
#q2
#a
array = np.array([[1, -2, 3],[-4, 5, -6]]);

#(i)
print(np.abs(array));
print("\n");

#(ii)
#array=array.flatten();
print(np.quantile(array,0.25));
print(np.quantile(array,0.50));
print(np.quantile(array,0.75));
print("\n");

#(iii)
#row-wise
print(np.mean(array,axis=1));
print(np.median(array,axis=1));
print(np.std(array,axis=1));

print("\n");
#column-wise
print(np.mean(array,axis=0));
print(np.median(array,axis=0));
print(np.std(array,axis=0));

[[1 2 3]
 [4 5 6]]


-3.5
-0.5
2.5


[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]


In [ ]:
#b
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]);
print(np.floor(a));
print(np.ceil(a));
print(np.trunc(a));
print(np.round(a));

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#q3
#a
array = np.array([10, 52, 62, 16, 16, 54, 453]);
arr_sort=np.sort(array);
print(np.sort(array));
print(np.argsort(array));
print(arr_sort[:4])
print(arr_sort[-5:]);

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [ ]:
#b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]);
print(array[array == array.astype(int)]);
print(array[array != array.astype(int)]);

[1. 2. 3. 2.]
[1.2 2.2]


In [ ]:
from PIL import Image

In [ ]:
image = Image.open

In [ ]:
#q4
def img_to_array(path):
  import keras
  from keras.preprocessing.image import load_img

  img = load_img(path)
  print(type(img))
  print(img.format)
  print(img.mode)
  print(img.size)
  img.show()

  # resizing image
  imgr = img.resize([30, 30])
  print(imgr.size)

  # converting image to array
  from keras.preprocessing.image import img_to_array
  imgarr = img_to_array(img)
  print(imgarr.shape)

  # saving image
  from keras.preprocessing.image import save_img
  save_img('charu.png', imgarr)

  # converting to grayscale 
  # img_gray = load_img(path, grayscale = True)
  # img_gray_arr = img_to_array(img_gray)
  # save_img('corvette_grayscale.jpg', img_gray_arr)


img_to_array('/content/bloodproject.png')

<class 'PIL.Image.Image'>
None
RGB
(225, 225)
(30, 30)
(225, 225, 3)
